services:
  classifier:
    image: cacophonyproject/classifier
    # Keeps the container idle but active indefinitely
    # command: tail -F /dev/null 
    # Optional: ensures it restarts if the server reboots or it crashes
    restart: always 
