name: Processing Release
run-name: Build classProcessingifier
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
     
      - run: sudo apt-get update
      - run: python -m pip install --upgrade pip
      
      - run: pip install black --upgrade
        
      - name: Install dependencies
        run: |
          pip install pex==2.1.90
          pip install -r requirements.txt
     

      - name: Run tests
        run: pytest -s

  pex-build:
    name: Build distribution 📦
    runs-on: ubuntu-latest
    needs:
      - tests
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        architecture: 'x64'

                
    - name: Install dependencies
      run: |
        pip install pex==2.1.90
        pip install -r requirements.txt
   
    - name: Install NFPM
    - run: |
        echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
        sudo apt update
        sudo apt install nfpm

    - name: Install pypa/build
      run: _release/build ${{ github.ref }}

